### ISSUE TITLE
Wrong Description in DNA Fingerprint wiki

### ISSUE THREAD

**Issue by flystar233** [gc5k/GEAR#3]
--m Specify the number of markers for generating similarity scores between individuals. It defaults to use all markers.
but It defaults to use 100 markers……

--low-cutoff/--l

Specify the lower bounder for similarity cutoff. Only the similarity score **lower** than the given cutoff will be printed out.

--high-cutoff/--h

Specify the upper bounder for similarity cutoff. Only the similarity score **lower higher** than the given cutoff will be printed out.

**Comment by gc5k** [comment]
> --m Specify the number of markers for generating similarity scores between individuals. It defaults to use all markers.
> but It defaults to use 100 markers……
> 
> --low-cutoff/--l
> 
> Specify the lower bounder for similarity cutoff. Only the similarity score **lower** than the given cutoff will be printed out.
> 
> --high-cutoff/--h
> 
> Specify the upper bounder for similarity cutoff. Only the similarity score **lower higher** than the given cutoff will be printed out.

All fixed according to your suggested.
Thanks.

**Comment by gc5k** [comment]
> --m Specify the number of markers for generating similarity scores between individuals. It defaults to use all markers.
> but It defaults to use 100 markers……
> 
> --low-cutoff/--l
> 
> Specify the lower bounder for similarity cutoff. Only the similarity score **lower** than the given cutoff will be printed out.
> 
> --high-cutoff/--h
> 
> Specify the upper bounder for similarity cutoff. Only the similarity score **lower higher** than the given cutoff will be printed out.

Who are you? From BGI?

**Comment by flystar233** [comment]
> > --m Specify the number of markers for generating similarity scores between individuals. It defaults to use all markers.
> > but It defaults to use 100 markers……
> > --low-cutoff/--l
> > Specify the lower bounder for similarity cutoff. Only the similarity score **lower** than the given cutoff will be printed out.
> > --high-cutoff/--h
> > Specify the upper bounder for similarity cutoff. Only the similarity score **lower higher** than the given cutoff will be printed out.
> 
> Who are you? From BGI?

Yes, I am from BGI-shenzhen. I'm browsing through recent GWAS articles. One article mentions Eigen GWAS that I can't understand, so I found your github. You've done a good job and solved a lot of needs.

**Comment by gc5k** [comment]
Thanks for the appreciation.
