### ISSUE TITLE
two *.egwas files?

### ISSUE THREAD

**Issue by shenweima** [gc5k/GEAR#4]
I do eigengwas analysis for my wheat population. The  population included two subgroup.
 
The commond is `jar gear.jar eigengwas --bfile MCC_genotype_filter2 --inbred --ev 2 --out wheat125` 

The result included two files wheat125.1.egwas and wheat125.1.egwas.
 
Could you tell me which file is right?

**Comment by gc5k** [comment]
"The result included two files wheat125.**1**.egwas and wheat125.**1**.egwas."

Should it read "wheat125.**1**.egwas" and "wheat125.**2**.egwas", respectively according to your command?

1 and 2 for the scan for eigenvector 1 and 2 respectively.

You can contact me via chenguobo@gmail.com directly.

**Comment by shenweima** [comment]
Thanks
